"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { formatCurrency } from "@/lib/format";

type Profile = { id: string; full_name: string; email: string; status: string; portfolio_value: number };
type Activity = { id: string; title: string; body: string; category: string };

export default function AdminOverviewPage() {
  const [users, setUsers] = useState<Profile[]>([]);
  const [activity, setActivity] = useState<Activity[]>([]);
  const [supportCount, setSupportCount] = useState(0);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { async function load() { const supabase = createClient(); const [{ data: profiles, error: profileError }, { data: notifications, error: notificationError }, { count, error: supportError }] = await Promise.all([supabase.from("profiles").select("id, full_name, email, status, portfolio_value").order("created_at", { ascending: false }), supabase.from("notifications").select("id, title, body, category").eq("audience", "admin").order("created_at", { ascending: false }).limit(4), supabase.from("support_messages").select("id", { count: "exact", head: true }).eq("sender", "user")]); if (profileError || notificationError || supportError) setError(profileError?.message ?? notificationError?.message ?? supportError?.message ?? "Unable to load overview."); else { setUsers(profiles ?? []); setActivity(notifications ?? []); setSupportCount(count ?? 0); } } void load(); }, []);
  const pending = users.filter((user) => user.status === "Pending").length;
  const verified = users.filter((user) => user.status === "Verified").length;
  const totalValue = users.reduce((sum, user) => sum + Number(user.portfolio_value || 0), 0);
  const stats = [{ label: "Total users", value: users.length, href: "/admin/users" }, { label: "Pending verification", value: pending, href: "/admin/users" }, { label: "Verified users", value: verified, href: "/admin/users" }, { label: "Total portfolio value", value: formatCurrency(totalValue), href: "/admin/users" }];
  return <div><div className="mb-8"><p className="font-mono text-gold text-[11px] mb-2">ADMIN DASHBOARD</p><h1 className="font-serif text-[26px] md:text-[32px]">Overview</h1><p className="text-paper-dim text-[14px] mt-2">Monitor accounts and customer activity from one place.</p></div>{error ? <p className="text-rust">{error}</p> : <><div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-3 mb-8">{stats.map((stat) => <Link key={stat.label} href={stat.href} className="bg-slate border border-line hover:border-gold px-5 py-5"><div className="font-mono text-[11px] text-paper-dim uppercase">{stat.label}</div><div className="font-serif text-[26px] mt-2">{stat.value}</div></Link>)}</div><div className="grid grid-cols-1 lg:grid-cols-[1.25fr_0.75fr] gap-6"><section className="border border-line"><div className="flex items-center justify-between px-5 py-4 border-b border-line"><div><h2 className="font-serif text-[20px]">Recent accounts</h2><p className="text-[12px] text-paper-dim mt-1">Latest registered customers</p></div><Link href="/admin/users" className="text-gold text-[13px]">View users →</Link></div>{users.slice(0, 5).map((user) => <Link key={user.id} href={`/admin/users/${user.id}`} className="flex items-center gap-3 px-5 py-4 border-b last:border-b-0 border-line hover:bg-slate"><div className="w-8 h-8 rounded-full border border-line bg-slate-2 flex items-center justify-center text-gold font-mono text-[11px]">{(user.full_name || user.email).slice(0, 1).toUpperCase()}</div><div className="min-w-0 flex-1"><p className="text-[14px] truncate">{user.full_name || "Unnamed user"}</p><p className="text-[12px] text-paper-dim truncate">{user.email}</p></div><span className={`text-[11px] font-mono ${user.status === "Verified" ? "text-moss" : "text-gold"}`}>{user.status}</span></Link>)}{users.length === 0 && <p className="p-5 text-paper-dim text-[13px]">No users yet.</p>}</section><section className="border border-line"><div className="px-5 py-4 border-b border-line"><h2 className="font-serif text-[20px]">Activity</h2><p className="text-[12px] text-paper-dim mt-1">Latest tasks requiring attention</p></div><Link href="/admin/support" className="block px-5 py-4 border-b border-line hover:bg-slate"><span className="text-[11px] font-mono text-gold">SUPPORT</span><p className="text-[14px] mt-1">{supportCount} customer messages</p></Link>{activity.map((notification) => <Link key={notification.id} href="/admin/notifications" className="block px-5 py-4 border-b last:border-b-0 border-line hover:bg-slate"><span className="text-[11px] font-mono text-gold">{notification.category.toUpperCase()}</span><p className="text-[14px] mt-1">{notification.title}</p><p className="text-[12px] text-paper-dim mt-1 line-clamp-2">{notification.body}</p></Link>)}{activity.length === 0 && <p className="p-5 text-paper-dim text-[13px]">No recent activity.</p>}</section></div></>}</div>;
}
